#!/usr/bin/python3
"""pwiki 진입점. /usr/bin/python3(표준 라이브러리만)로 돈다."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from pwikilib.cli import main  # noqa: E402

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
